package com.mibolsa.mavenbolsa;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

/**
 *
 * @author MIGUELANGEL DE JESUS
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.getContentPane().setBackground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloMenu = new javax.swing.JLabel();
        BtnUna = new javax.swing.JButton();
        SeleccionarAccion = new javax.swing.JComboBox<>();
        BtnTodas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mi Bolsa");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.foreground"));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setLocation(new java.awt.Point(500, 200));

        TituloMenu.setBackground(new java.awt.Color(0, 102, 102));
        TituloMenu.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        TituloMenu.setForeground(new java.awt.Color(153, 153, 153));
        TituloMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloMenu.setText("Mi Bolsa");
        TituloMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        BtnUna.setText("Acciones");
        BtnUna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnUnaMouseClicked(evt);
            }
        });
        BtnUna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUnaActionPerformed(evt);
            }
        });

        SeleccionarAccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRODUCTOS EFE S.A.", "PROAGRO C.A.", "PROTINAL C.A.", "C.A. RON SANTA TERESA", "CERAMICA CARABOBO, SACA", "CORP.GRUPO QUIMICO, C.A.", "CORIMON, C.A.", "DOMINGUEZ & CIA., S.A.", "ENVASES VENEZOLANOS S.A.", "FABRICA NACIONAL DE CEMENTOS, C.A.", "MANUFACTURAS DE PAPEL,C.A.(MANPA) SACA.", "SIVENSA, S.A", "C.A. TELARES DE PALO GRANDE", "CORP. INDUSTRIAL DE ENERGIA CA SACA", "C.A.NAC.TELF.VZLA. (CANTV) CLASE (D)", "BCO.OCC.DE DESCUENTO, BCO. UNIVERSAL", "MERCANTIL SERV. FINANCIEROS C.A. CLS.(A)", "MERCANTIL SERV. FINANCIEROS C.A. CLS.(B)", "BANCO DEL CARIBE,C.A.BCO.UNIV.CLASE (A)", "BANCO NACIONAL DE CREDITO,C.A.BCO.UNIV.", "BANCO PROVINCIAL, S.A. BCO. UNIVERSAL", "BANCO DE VENEZUELA, S.A. BCO.UNIVERSAL", "BOLSA DE VALORES DE CARACAS, C.A.", "GRUPO ZULIANO, C.A.", "FONDO DE VALORES INMOB.,SACA. CLASE (A)", "FONDO DE VALORES INMOB.,SACA. CLASE (B)", "INVACA,INMUEBLES,VALORES Y CAPITALES,", " " }));
        SeleccionarAccion.setSelectedItem(SeleccionarAccion);
        SeleccionarAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarAccionActionPerformed(evt);
            }
        });

        BtnTodas.setBackground(new java.awt.Color(255, 204, 25));
        BtnTodas.setText("Todas");
        BtnTodas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnTodasMouseClicked(evt);
            }
        });
        BtnTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTodasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(TituloMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SeleccionarAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnTodas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnUna))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(TituloMenu)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeleccionarAccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnUna))
                .addGap(34, 34, 34)
                .addComponent(BtnTodas)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnUnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUnaActionPerformed

    private void BtnUnaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnUnaMouseClicked
        try {
       
            Conexion.EstablecerConexion(SeleccionarAccion.getSelectedIndex ());           

// Accion AccionConsultada = new Accion();
          //  AccionConsultada.setEmpresa (SeleccionarAccion.getSelectedIndex());
           // AccionConsultada.setUltimoPrecio (SeleccionarAccion.getSelectedIndex());
            
            
            AccionInterface Hola = new AccionInterface ();
            
            Hola.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
      
      
      
        
          
        
    }//GEN-LAST:event_BtnUnaMouseClicked

    private void SeleccionarAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarAccionActionPerformed

String [] acciones = new String [27];


acciones[0]="PRODUCTOS EFE S.A.";
acciones [1] = "PROAGRO C.A.";
acciones [2] = "PROTINAL C.A.";
acciones [3]= "C.A. RON SANTA TERESA";
acciones [4]= "CERAMICA CARABOBO, SACA";
acciones [5]= "CORP.GRUPO QUIMICO, C.A.";
acciones [6]= "CORIMON, C.A.";
acciones [7]= "DOMINGUEZ & CIA., S.A.";
acciones [8]= "ENVASES VENEZOLANOS S.A.";
acciones [9]= "FABRICA NACIONAL DE CEMENTOS, C.A.";
acciones [10]= "MANUFACTURAS DE PAPEL,C.A.(MANPA) SACA.";
acciones [11]= "SIVENSA, S.A";
acciones [12]= "C.A. TELARES DE PALO GRANDE";
acciones [13]= "CORP. INDUSTRIAL DE ENERGIA CA SACA";
acciones [14]= "C.A.NAC.TELF.VZLA. (CANTV) CLASE (D)";
acciones [15]= "BCO.OCC.DE DESCUENTO, BCO. UNIVERSAL";
acciones [16]= "MERCANTIL SERV. FINANCIEROS C.A. CLS.(A)";
acciones [17]= "MERCANTIL SERV. FINANCIEROS C.A. CLS.(B)";
acciones [18]= "BANCO DEL CARIBE,C.A.BCO.UNIV.CLASE (A)";
acciones [19]= "BANCO NACIONAL DE CREDITO,C.A.BCO.UNIV.";
acciones [20]= "BANCO PROVINCIAL, S.A. BCO. UNIVERSAL";
acciones [21]= "BANCO DE VENEZUELA, S.A. BCO.UNIVERSAL";
acciones [22]= "BOLSA DE VALORES DE CARACAS, C.A.";
acciones [23]= "GRUPO ZULIANO, C.A.";
acciones [24]= "FONDO DE VALORES INMOB.,SACA. CLASE (A)";
acciones [25]= "FONDO DE VALORES INMOB.,SACA. CLASE (B)";
acciones [26]= "INVACA,INMUEBLES,VALORES Y CAPITALES,";


SeleccionarAccion.addItem (acciones[0]);
SeleccionarAccion.addItem (acciones[1]);
SeleccionarAccion.addItem (acciones[2]);
SeleccionarAccion.addItem (acciones[3]);
SeleccionarAccion.addItem (acciones[4]);
SeleccionarAccion.addItem (acciones[5]);
SeleccionarAccion.addItem (acciones[6]);
SeleccionarAccion.addItem (acciones[7]);
SeleccionarAccion.addItem (acciones[8]);
SeleccionarAccion.addItem (acciones[9]);
SeleccionarAccion.addItem (acciones[10]);
SeleccionarAccion.addItem (acciones[11]);
SeleccionarAccion.addItem (acciones[12]);
SeleccionarAccion.addItem (acciones[13]);
SeleccionarAccion.addItem (acciones[14]);
SeleccionarAccion.addItem (acciones[15]);
SeleccionarAccion.addItem (acciones[16]);
SeleccionarAccion.addItem (acciones[17]);
SeleccionarAccion.addItem (acciones[18]);
SeleccionarAccion.addItem (acciones[19]);
SeleccionarAccion.addItem (acciones[20]);
SeleccionarAccion.addItem (acciones[21]);
SeleccionarAccion.addItem (acciones[22]);
SeleccionarAccion.addItem (acciones[23]);
SeleccionarAccion.addItem (acciones[24]);
SeleccionarAccion.addItem (acciones[25]);
SeleccionarAccion.addItem (acciones[26]);


JComboBox indiceAccion = new JComboBox (acciones);


        // TODO add your handling code here:
    }//GEN-LAST:event_SeleccionarAccionActionPerformed

    private void BtnTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTodasActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTodasActionPerformed

    private void BtnTodasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTodasMouseClicked
        // TODO add your handling code here:
        InterfaceTodas interfacetodas = null;
        try {
            interfacetodas = new InterfaceTodas ();
        } catch (IOException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        interfacetodas.setVisible (true);
    
        
    }//GEN-LAST:event_BtnTodasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTodas;
    private javax.swing.JButton BtnUna;
    private javax.swing.JComboBox<String> SeleccionarAccion;
    private javax.swing.JLabel TituloMenu;
    // End of variables declaration//GEN-END:variables
}
